export default [
  // home
  '/image/fight2/home/info-bg.png',
  '/image/fight2/home/home-bottom.png',
  '/image/fight2/home/buton1-0.png',
  '/image/fight2/home/buton1-1.png',
  '/image/fight2/home/buton2-0.png',
  '/image/fight2/home/buton2-1.png',
  // wait
  '/image/fight2/wait.gif',
  '/image/fight2/wait-online/invite-other-0.png',
  '/image/fight2/wait-online/go-simulate-0.png',
  '/image/fight2/wait-online/start-0.png',
  '/image/fight2/wait-online/hand.gif',
  '/image/fight2/wait-online/status-wait-time-pic.png',
  '/image/fight2/wait-online/status-success-pic.png',
  '/image/fight2/wait-online/bg.png',
  '/image/fight2/wait-online/go-simulate-1.png',
  '/image/fight2/wait-online/invite-other-1.png',
  '/image/fight2/wait-online/start-1.png',
  '/image/fight2/wait-online/wenhao.png',
  // ready
  '/image/fight2/ready/ready-bg.png',
  '/image/fight2/ready/me-bg.png',
  '/image/fight2/ready/him-bg.png',
  '/image/fight2/ready/vs.png',
  // fight
  '/image/fight2/fight/correct.png',
  '/image/fight2/fight/error.png',
  '/image/fight2/fight/questions-number-bg.png',
  '/image/fight2/fight/timer-bg.jpg',
  '/image/fight2/fight/double.png',
  // result
  '/image/fight2/result/two-dots.png',
  '/image/fight2/result/top-bg.png',
  '/image/fight2/result/share-0.png',
  '/image/fight2/result/share-1.png',
  '/image/fight2/result/goon-0.png',
  '/image/fight2/result/goon-1.png',
  '/image/fight2/result/brushTheQuestion.png',
  '/image/fight2/result/challengeFriend.png',
  '/image/fight2/result/fightfriend.png',
  '/image/fight2/result/LOSE.png',
  '/image/fight2/result/FINAL_HIT.png',
  '/image/fight2/result/WIN_MARGIN.png',
  '/image/fight2/result/DRAW.png',
  '/image/fight2/result/WIN.png',
  // common
  '/image/fight2/common/star.png',
  '/image/fight2/common/medal/iron.png',
  '/image/fight2/common/medal/bronze.png',
  '/image/fight2/common/medal/silver.png',
  '/image/fight2/common/medal/gold.png',
  '/image/fight2/common/medal/platinum.png',
  '/image/fight2/common/medal/diamonds.png',
  '/image/fight2/common/medal/star.png',
  '/image/fight2/common/medal/king.png',
  '/image/fight2/common/medal/default.png',
  '/image/fight2/common/me-bg.png',
  '/image/fight2/common/me-lose-bg.png',
  '/image/fight2/common/him-bg.png',
  '/image/fight2/common/him-lose-bg.png',
  // list
  '/image/fight2/list/pkListBg.png',
  '/image/fight2/list/star2.png',
  // danIntro
  '/image/fight2/danIntro/danIntro.png'
]
